ALTER TABLE vod_movies
    ADD COLUMN IF NOT EXISTS resolution TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS video_codec TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS audio_codec TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_quality TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS hdr TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS bitrate_kbps INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS width INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS height INT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS vod_movies_resolution_idx ON vod_movies (resolution);
